/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.ProjectApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectApi', function() {
    describe('deleteV1ProjectId', function() {
      it('should call deleteV1ProjectId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ProjectId
        //instance.deleteV1ProjectId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ProjectId', function() {
      it('should call getV1ProjectId successfully', function(done) {
        //uncomment below and update the code to test getV1ProjectId
        //instance.getV1ProjectId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1Project', function() {
      it('should call postV1Project successfully', function(done) {
        //uncomment below and update the code to test postV1Project
        //instance.postV1Project(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ProjectId', function() {
      it('should call putV1ProjectId successfully', function(done) {
        //uncomment below and update the code to test putV1ProjectId
        //instance.putV1ProjectId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
